$axure.loadCurrentPage({
  "url":"框架.html",
  "generationDate":new Date(1454076571840.97),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e2cceeee454d4910a819caa3cde6f6e9",
    "type":"Axure:Page",
    "name":"框架",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f714a6d23d4949358f9c4ca462260605",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":67,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ab8be2da4cf4784a6fa60e54da135cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":50},
                "size":{
                  "width":67,
                  "height":73}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 应用管理 在 (内部框架)",
                      "linkType":"frame",
                      "framesToTargets":[{
                          "framePath":["3433e99bb6104168be58dc1af5143752"],
                          "target":{
                            "targetType":"page",
                            "url":"应用管理.html",
                            "includeVariables":true}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/框架/u0.png"}},
{
          "id":"3f1d507b9a41452ca01b9ee71910a811",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":0,
              "y":123},
            "size":{
              "width":67,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8be10f463f64f3fa447f7514d24e8ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":0,
                  "y":123},
                "size":{
                  "width":67,
                  "height":73}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 视频收录和存储 在 (内部框架)",
                      "linkType":"frame",
                      "framesToTargets":[{
                          "framePath":["3433e99bb6104168be58dc1af5143752"],
                          "target":{
                            "targetType":"page",
                            "url":"视频收录和存储.html",
                            "includeVariables":true}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/框架/u0.png"}},
{
          "id":"c2625341875a4c1c8268383a8fbd80ed",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":0,
              "y":196},
            "size":{
              "width":67,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86c5d6c2d94a41c5aeadac61e513e122",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":0,
                  "y":196},
                "size":{
                  "width":67,
                  "height":73}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 内容管理和加工 在 (内部框架)",
                      "linkType":"frame",
                      "framesToTargets":[{
                          "framePath":["3433e99bb6104168be58dc1af5143752"],
                          "target":{
                            "targetType":"page",
                            "url":"内容管理和加工.html",
                            "includeVariables":true}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/框架/u0.png"}},
{
          "id":"25280d15a2bd4a378333707574396811",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":0,
              "y":269},
            "size":{
              "width":67,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e39260f65f774ee2a4487615eeac4e24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":0,
                  "y":269},
                "size":{
                  "width":67,
                  "height":73}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 播放器管理 在 (内部框架)",
                      "linkType":"frame",
                      "framesToTargets":[{
                          "framePath":["3433e99bb6104168be58dc1af5143752"],
                          "target":{
                            "targetType":"page",
                            "url":"播放器管理.html",
                            "includeVariables":true}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/框架/u0.png"}},
{
          "id":"5b4b80af14304b158b7575431ce25add",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":0,
              "y":342},
            "size":{
              "width":67,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5ec755dc53941ab996741f5333463b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":0,
                  "y":342},
                "size":{
                  "width":67,
                  "height":73}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 P2P网络管理 在 (内部框架)",
                      "linkType":"frame",
                      "framesToTargets":[{
                          "framePath":["3433e99bb6104168be58dc1af5143752"],
                          "target":{
                            "targetType":"page",
                            "url":"p2p网络管理.html",
                            "includeVariables":true}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/框架/u0.png"}},
{
          "id":"091624feeba14e0aa9d20dddc79775d1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":0,
              "y":415},
            "size":{
              "width":67,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb5fcadad85e40f2bad07720c104debd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":0,
                  "y":415},
                "size":{
                  "width":67,
                  "height":73}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 网页和视频加速 在 (内部框架)",
                      "linkType":"frame",
                      "framesToTargets":[{
                          "framePath":["3433e99bb6104168be58dc1af5143752"],
                          "target":{
                            "targetType":"page",
                            "url":"网页和视频加速.html",
                            "includeVariables":true}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/框架/u0.png"}},
{
          "id":"b19a9e5c475743d19e9afb8282f1cc96",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":0,
              "y":488},
            "size":{
              "width":67,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24adc4da26134b56bf4a3cc56640d792",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":0,
                  "y":488},
                "size":{
                  "width":67,
                  "height":73}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 播出控制 在 (内部框架)",
                      "linkType":"frame",
                      "framesToTargets":[{
                          "framePath":["3433e99bb6104168be58dc1af5143752"],
                          "target":{
                            "targetType":"page",
                            "url":"播出控制.html",
                            "includeVariables":true}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/框架/u0.png"}},
{
          "id":"f470316245a0480d91ccdb329ebc3287",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":0,
              "y":561},
            "size":{
              "width":67,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42f910fd128645c4abc545402566c196",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":0,
                  "y":561},
                "size":{
                  "width":67,
                  "height":73}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 用户账户 在 (内部框架)",
                      "linkType":"frame",
                      "framesToTargets":[{
                          "framePath":["3433e99bb6104168be58dc1af5143752"],
                          "target":{
                            "targetType":"page",
                            "url":"用户账户.html",
                            "includeVariables":true}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/框架/u0.png"}},
{
          "id":"3433e99bb6104168be58dc1af5143752",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":50},
            "size":{
              "width":510,
              "height":584}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "f714a6d23d4949358f9c4ca462260605":{
      "scriptId":"u0"},
    "8ab8be2da4cf4784a6fa60e54da135cf":{
      "scriptId":"u1"},
    "3f1d507b9a41452ca01b9ee71910a811":{
      "scriptId":"u2"},
    "d8be10f463f64f3fa447f7514d24e8ab":{
      "scriptId":"u3"},
    "c2625341875a4c1c8268383a8fbd80ed":{
      "scriptId":"u4"},
    "86c5d6c2d94a41c5aeadac61e513e122":{
      "scriptId":"u5"},
    "25280d15a2bd4a378333707574396811":{
      "scriptId":"u6"},
    "e39260f65f774ee2a4487615eeac4e24":{
      "scriptId":"u7"},
    "5b4b80af14304b158b7575431ce25add":{
      "scriptId":"u8"},
    "a5ec755dc53941ab996741f5333463b8":{
      "scriptId":"u9"},
    "091624feeba14e0aa9d20dddc79775d1":{
      "scriptId":"u10"},
    "bb5fcadad85e40f2bad07720c104debd":{
      "scriptId":"u11"},
    "b19a9e5c475743d19e9afb8282f1cc96":{
      "scriptId":"u12"},
    "24adc4da26134b56bf4a3cc56640d792":{
      "scriptId":"u13"},
    "f470316245a0480d91ccdb329ebc3287":{
      "scriptId":"u14"},
    "42f910fd128645c4abc545402566c196":{
      "scriptId":"u15"},
    "3433e99bb6104168be58dc1af5143752":{
      "scriptId":"u16"}}});