$axure.loadCurrentPage({
  "url":"云媒体服务平台.html",
  "generationDate":new Date(1454076571624.92),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1e4bfe1276d3499488a7848ba1046fae",
    "type":"Axure:Page",
    "name":"云媒体服务平台",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4f3a61f36bdd4c25b2933053a15554f0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":30},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"152955773ff241189cbf4fe01da966c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":650,
              "y":38},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b72e701cb2e74aeca1038ed26eb28c70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":650,
                  "y":38},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50d44f114f2e499eab7ac3b3ac3baa7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":38},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc0f56026319432d98eaa588b41dbfa1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":700,
                  "y":38},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b3e30e39c4054892a0fd00c7b0e784db",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":38},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba378a46534d46d9b6934ff263420446",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":780,
                  "y":38},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e1bafbb6e6a8401995949352934c0b63",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":90},
            "size":{
              "width":142,
              "height":133}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c808bf1ad6fd48dfac9d5421f5978c36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":90},
                "size":{
                  "width":142,
                  "height":133}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/云媒体服务平台/u7.png"}},
{
          "id":"66a0a0983252451f9ac81deea6ff16c9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":363,
              "y":90},
            "size":{
              "width":142,
              "height":133}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3525c1f99e034357aacfa79b77668ecb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":363,
                  "y":90},
                "size":{
                  "width":142,
                  "height":133}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/云媒体服务平台/u7.png"}},
{
          "id":"c2aff22f3e3e4404a719454d4b568c68",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":535,
              "y":90},
            "size":{
              "width":142,
              "height":133}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f847c4eed18945c5b96afd87577f85ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":535,
                  "y":90},
                "size":{
                  "width":142,
                  "height":133}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/云媒体服务平台/u7.png"}},
{
          "id":"6527f5af89f74403b5cffc222c29c777",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":718,
              "y":90},
            "size":{
              "width":142,
              "height":133}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44eccc00794a42648ad2eda9994899b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":718,
                  "y":90},
                "size":{
                  "width":142,
                  "height":133}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/云媒体服务平台/u7.png"}},
{
          "id":"eca9d7d5a6ac40e7add0f22927a10ec9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":190,
              "y":267},
            "size":{
              "width":142,
              "height":133}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c864810ea852496d82ec520447983046",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":190,
                  "y":267},
                "size":{
                  "width":142,
                  "height":133}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/云媒体服务平台/u7.png"}},
{
          "id":"3ce2ec3355694d7aa022a90693bf1453",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":363,
              "y":267},
            "size":{
              "width":142,
              "height":133}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bef51dc741b49dbb1c1c6505c6e2a2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":363,
                  "y":267},
                "size":{
                  "width":142,
                  "height":133}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/云媒体服务平台/u7.png"}},
{
          "id":"78609da87335494bba07d62e772bbfcc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":535,
              "y":267},
            "size":{
              "width":142,
              "height":133}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"084898d0633447ec8e6a889928c31e09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":535,
                  "y":267},
                "size":{
                  "width":142,
                  "height":133}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/云媒体服务平台/u7.png"}},
{
          "id":"a4832da8c418493a9ec94ec14ec13933",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":718,
              "y":267},
            "size":{
              "width":142,
              "height":133}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2b33e15f3644b3fb6edc79639168dbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":718,
                  "y":267},
                "size":{
                  "width":142,
                  "height":133}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/云媒体服务平台/u7.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "4f3a61f36bdd4c25b2933053a15554f0":{
      "scriptId":"u0"},
    "152955773ff241189cbf4fe01da966c4":{
      "scriptId":"u1"},
    "b72e701cb2e74aeca1038ed26eb28c70":{
      "scriptId":"u2"},
    "50d44f114f2e499eab7ac3b3ac3baa7b":{
      "scriptId":"u3"},
    "bc0f56026319432d98eaa588b41dbfa1":{
      "scriptId":"u4"},
    "b3e30e39c4054892a0fd00c7b0e784db":{
      "scriptId":"u5"},
    "ba378a46534d46d9b6934ff263420446":{
      "scriptId":"u6"},
    "e1bafbb6e6a8401995949352934c0b63":{
      "scriptId":"u7"},
    "c808bf1ad6fd48dfac9d5421f5978c36":{
      "scriptId":"u8"},
    "66a0a0983252451f9ac81deea6ff16c9":{
      "scriptId":"u9"},
    "3525c1f99e034357aacfa79b77668ecb":{
      "scriptId":"u10"},
    "c2aff22f3e3e4404a719454d4b568c68":{
      "scriptId":"u11"},
    "f847c4eed18945c5b96afd87577f85ad":{
      "scriptId":"u12"},
    "6527f5af89f74403b5cffc222c29c777":{
      "scriptId":"u13"},
    "44eccc00794a42648ad2eda9994899b1":{
      "scriptId":"u14"},
    "eca9d7d5a6ac40e7add0f22927a10ec9":{
      "scriptId":"u15"},
    "c864810ea852496d82ec520447983046":{
      "scriptId":"u16"},
    "3ce2ec3355694d7aa022a90693bf1453":{
      "scriptId":"u17"},
    "8bef51dc741b49dbb1c1c6505c6e2a2f":{
      "scriptId":"u18"},
    "78609da87335494bba07d62e772bbfcc":{
      "scriptId":"u19"},
    "084898d0633447ec8e6a889928c31e09":{
      "scriptId":"u20"},
    "a4832da8c418493a9ec94ec14ec13933":{
      "scriptId":"u21"},
    "f2b33e15f3644b3fb6edc79639168dbe":{
      "scriptId":"u22"}}});