$axure.loadCurrentPage({
  "url":"视频收录和存储.html",
  "generationDate":new Date(1454076572313.16),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6c8af92856854cacaaaac77c195e4a66",
    "type":"Axure:Page",
    "name":"视频收录和存储",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"352399bc95004961ada6ea11c3e4797d",
          "label":"文件收录",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":80},
            "size":{
              "width":200,
              "height":300}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 文件收录 to 显示",
                      "panelsToStates":[{
                          "panelPath":["352399bc95004961ada6ea11c3e4797d"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"686afd871cd64fd2b8ffdde5d751d5fb",
              "label":"隐藏",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"95d70dcf6fb2486abdde38f475f9d29b",
                  "label":"",
                  "parentDynamicPanel":"352399bc95004961ada6ea11c3e4797d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0099FF},
                    "size":{
                      "width":200,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6ce171d57ef14f6f915f44123526eaac",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"352399bc95004961ada6ea11c3e4797d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF0099FF},
                        "size":{
                          "width":200,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 文件收录 to 显示",
                              "panelsToStates":[{
                                  "panelPath":["352399bc95004961ada6ea11c3e4797d"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]},
{
                              "action":"moveWidget",
                              "description":"移动 直播收录 相对位置为 (0,250)",
                              "objectsToMoves":[{
                                  "objectPath":["840ed94c9e01406cb55d77317c1f5f8d"],
                                  "moveInfo":{
                                    "moveType":"delta",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"250",
                                      "stos":[]},
                                    "options":{
}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/应用管理/u1.png"}}]},
{
              "id":"69e3c1f1944f4e3c9b5296e6bd77e9b6",
              "label":"显示",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6b557143dfd841ad9abd75ea4debfbaa",
                  "label":"",
                  "parentDynamicPanel":"352399bc95004961ada6ea11c3e4797d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0099FF},
                    "size":{
                      "width":200,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f788d56056174dde8b279b7902646334",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"352399bc95004961ada6ea11c3e4797d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF0099FF},
                        "size":{
                          "width":200,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 文件收录 to 隐藏",
                              "panelsToStates":[{
                                  "panelPath":["352399bc95004961ada6ea11c3e4797d"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]},
{
                              "action":"moveWidget",
                              "description":"移动 直播收录 相对位置为 (0,-250)",
                              "objectsToMoves":[{
                                  "objectPath":["840ed94c9e01406cb55d77317c1f5f8d"],
                                  "moveInfo":{
                                    "moveType":"delta",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"-250",
                                      "stos":[]},
                                    "options":{
}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/应用管理/u1.png"}},
{
                  "id":"759b2a11f0b34be3bbe44c4faecc0993",
                  "label":"",
                  "parentDynamicPanel":"352399bc95004961ada6ea11c3e4797d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCFF00},
                    "location":{
                      "x":0,
                      "y":50},
                    "size":{
                      "width":200,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7136fec2f40d461fa528255e37a3f864",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"352399bc95004961ada6ea11c3e4797d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCFF00},
                        "location":{
                          "x":0,
                          "y":50},
                        "size":{
                          "width":200,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/应用管理/u5.png"}},
{
                  "id":"99923469e55c48f78fce5ca19401c719",
                  "label":"",
                  "parentDynamicPanel":"352399bc95004961ada6ea11c3e4797d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCFF00},
                    "location":{
                      "x":0,
                      "y":100},
                    "size":{
                      "width":200,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"08c2644bdd044591a8e9e6a581a97bb1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"352399bc95004961ada6ea11c3e4797d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCFF00},
                        "location":{
                          "x":0,
                          "y":100},
                        "size":{
                          "width":200,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/应用管理/u5.png"}},
{
                  "id":"d5881283716240c8a6bdaa56e1b07632",
                  "label":"",
                  "parentDynamicPanel":"352399bc95004961ada6ea11c3e4797d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCFF00},
                    "location":{
                      "x":0,
                      "y":200},
                    "size":{
                      "width":200,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"84e859de4af74948a7694680bc44be03",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"352399bc95004961ada6ea11c3e4797d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCFF00},
                        "location":{
                          "x":0,
                          "y":200},
                        "size":{
                          "width":200,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/应用管理/u5.png"}},
{
                  "id":"0ba0b940c228414b948d4d1e769e20a5",
                  "label":"",
                  "parentDynamicPanel":"352399bc95004961ada6ea11c3e4797d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCFF00},
                    "location":{
                      "x":0,
                      "y":150},
                    "size":{
                      "width":200,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"483c139f5913425ba6c7396900f48bf2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"352399bc95004961ada6ea11c3e4797d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCFF00},
                        "location":{
                          "x":0,
                          "y":150},
                        "size":{
                          "width":200,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/应用管理/u5.png"}},
{
                  "id":"b97e1fb2361d48f8b8cf17616a4e96ec",
                  "label":"",
                  "parentDynamicPanel":"352399bc95004961ada6ea11c3e4797d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCFF00},
                    "location":{
                      "x":0,
                      "y":250},
                    "size":{
                      "width":200,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"db2bb6a962034795ba13f9b8efb1ff7d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"352399bc95004961ada6ea11c3e4797d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCFF00},
                        "location":{
                          "x":0,
                          "y":250},
                        "size":{
                          "width":200,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/应用管理/u5.png"}}]}]},
{
          "id":"840ed94c9e01406cb55d77317c1f5f8d",
          "label":"直播收录",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":130},
            "size":{
              "width":200,
              "height":250}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 直播收录 to 显示",
                      "panelsToStates":[{
                          "panelPath":["840ed94c9e01406cb55d77317c1f5f8d"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"328eadb04a6d4fe0ba71c4b98d226f52",
              "label":"隐藏",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"8ea1b9689d684efb8a7a37dbebcc6858",
                  "label":"",
                  "parentDynamicPanel":"840ed94c9e01406cb55d77317c1f5f8d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0099FF},
                    "size":{
                      "width":200,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c600aa36862b478eadc038f6b5e8fbe6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"840ed94c9e01406cb55d77317c1f5f8d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF0099FF},
                        "size":{
                          "width":200,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 直播收录 to 显示",
                              "panelsToStates":[{
                                  "panelPath":["840ed94c9e01406cb55d77317c1f5f8d"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/应用管理/u1.png"}}]},
{
              "id":"33b6e2ee98074603afaf0f7bf8451b14",
              "label":"显示",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c8f7ac989e454ea3903349c3475fef73",
                  "label":"",
                  "parentDynamicPanel":"840ed94c9e01406cb55d77317c1f5f8d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0099FF},
                    "size":{
                      "width":200,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5844dde0ff7246dba5e1982043dc46db",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"840ed94c9e01406cb55d77317c1f5f8d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF0099FF},
                        "size":{
                          "width":200,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 直播收录 to 隐藏",
                              "panelsToStates":[{
                                  "panelPath":["840ed94c9e01406cb55d77317c1f5f8d"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/应用管理/u1.png"}},
{
                  "id":"a50f44ff53c84963b52c90f7ca25f863",
                  "label":"",
                  "parentDynamicPanel":"840ed94c9e01406cb55d77317c1f5f8d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCFF00},
                    "location":{
                      "x":0,
                      "y":50},
                    "size":{
                      "width":200,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"31c5e2a2a3ea460296dd3dd2ae90bd5a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"840ed94c9e01406cb55d77317c1f5f8d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCFF00},
                        "location":{
                          "x":0,
                          "y":50},
                        "size":{
                          "width":200,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/应用管理/u5.png"}},
{
                  "id":"e67376e2fb064f47b05ccbeaa0db304f",
                  "label":"",
                  "parentDynamicPanel":"840ed94c9e01406cb55d77317c1f5f8d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCFF00},
                    "location":{
                      "x":0,
                      "y":100},
                    "size":{
                      "width":200,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4e46d99e4e404f54b01449c1089b4d44",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"840ed94c9e01406cb55d77317c1f5f8d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCFF00},
                        "location":{
                          "x":0,
                          "y":100},
                        "size":{
                          "width":200,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/应用管理/u5.png"}},
{
                  "id":"2a8faf11f9674b8394639fab79d41683",
                  "label":"",
                  "parentDynamicPanel":"840ed94c9e01406cb55d77317c1f5f8d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCFF00},
                    "location":{
                      "x":0,
                      "y":200},
                    "size":{
                      "width":200,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ea3c3bda4f7140eca7ff82728f5074aa",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"840ed94c9e01406cb55d77317c1f5f8d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCFF00},
                        "location":{
                          "x":0,
                          "y":200},
                        "size":{
                          "width":200,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/应用管理/u5.png"}},
{
                  "id":"f2a7c3e875d24deeaa9db5ef36450632",
                  "label":"",
                  "parentDynamicPanel":"840ed94c9e01406cb55d77317c1f5f8d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCFF00},
                    "location":{
                      "x":0,
                      "y":150},
                    "size":{
                      "width":200,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dfb8590769c34285a0cba723fac182ad",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"840ed94c9e01406cb55d77317c1f5f8d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCFF00},
                        "location":{
                          "x":0,
                          "y":150},
                        "size":{
                          "width":200,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/应用管理/u5.png"}}]}]},
{
          "id":"8ce0f625dc2642ceb49e7ff20f7f3f94",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":80},
            "size":{
              "width":760,
              "height":300}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "352399bc95004961ada6ea11c3e4797d":{
      "scriptId":"u0"},
    "95d70dcf6fb2486abdde38f475f9d29b":{
      "scriptId":"u1"},
    "6ce171d57ef14f6f915f44123526eaac":{
      "scriptId":"u2"},
    "6b557143dfd841ad9abd75ea4debfbaa":{
      "scriptId":"u3"},
    "f788d56056174dde8b279b7902646334":{
      "scriptId":"u4"},
    "759b2a11f0b34be3bbe44c4faecc0993":{
      "scriptId":"u5"},
    "7136fec2f40d461fa528255e37a3f864":{
      "scriptId":"u6"},
    "99923469e55c48f78fce5ca19401c719":{
      "scriptId":"u7"},
    "08c2644bdd044591a8e9e6a581a97bb1":{
      "scriptId":"u8"},
    "d5881283716240c8a6bdaa56e1b07632":{
      "scriptId":"u9"},
    "84e859de4af74948a7694680bc44be03":{
      "scriptId":"u10"},
    "0ba0b940c228414b948d4d1e769e20a5":{
      "scriptId":"u11"},
    "483c139f5913425ba6c7396900f48bf2":{
      "scriptId":"u12"},
    "b97e1fb2361d48f8b8cf17616a4e96ec":{
      "scriptId":"u13"},
    "db2bb6a962034795ba13f9b8efb1ff7d":{
      "scriptId":"u14"},
    "840ed94c9e01406cb55d77317c1f5f8d":{
      "scriptId":"u15"},
    "8ea1b9689d684efb8a7a37dbebcc6858":{
      "scriptId":"u16"},
    "c600aa36862b478eadc038f6b5e8fbe6":{
      "scriptId":"u17"},
    "c8f7ac989e454ea3903349c3475fef73":{
      "scriptId":"u18"},
    "5844dde0ff7246dba5e1982043dc46db":{
      "scriptId":"u19"},
    "a50f44ff53c84963b52c90f7ca25f863":{
      "scriptId":"u20"},
    "31c5e2a2a3ea460296dd3dd2ae90bd5a":{
      "scriptId":"u21"},
    "e67376e2fb064f47b05ccbeaa0db304f":{
      "scriptId":"u22"},
    "4e46d99e4e404f54b01449c1089b4d44":{
      "scriptId":"u23"},
    "2a8faf11f9674b8394639fab79d41683":{
      "scriptId":"u24"},
    "ea3c3bda4f7140eca7ff82728f5074aa":{
      "scriptId":"u25"},
    "f2a7c3e875d24deeaa9db5ef36450632":{
      "scriptId":"u26"},
    "dfb8590769c34285a0cba723fac182ad":{
      "scriptId":"u27"},
    "8ce0f625dc2642ceb49e7ff20f7f3f94":{
      "scriptId":"u28"}}});